// Hunt evidence data

export const huntEvidenceList = [
  { id: 'hunts_after_smudge_1', label: 'Hunts 1 minute after smudge (use timer under tools tab after smudging)', ghost: 'Demon' },
  { id: 'hunts_after_smudge_3', label: 'Hunts 3 minutes after smudge (use timer under tools tab after smudging)', ghost: 'Spirit' },
  { id: 'no_salt', label: 'Ghost cannot touch salt', ghost: 'Wraith' },
  { id: 'throws_far', label: 'Object thrown every 0.5 seconds and further than usual during hunt', ghost: 'Poltergeist' },
  { id: 'throws_multiple', label: 'Throws multiple objects at the same time', ghost: 'Poltergeist' },
  { id: 'disappears_photo', label: 'Disappears in photos', ghost: 'Phantom' },
  { id: 'less_visible_hunt', label: 'Less visible during hunts', ghost: 'Phantom' },
  { id: 'more_visible_hunt', label: 'More visible during hunts — blinks more often', ghost: 'Oni' },
  { id: 'no_ghost_mist', label: 'Never does ghost mist event', ghost: 'Oni' },
  { id: 'breath_breaker_off', label: 'Ghost has visible breath when breaker is off during hunts', ghost: 'Hantu' },
  { id: 'never_turns_on_breaker', label: 'Ghost never turns on breaker', ghost: 'Hantu' },
  { id: 'faster_cold_rooms', label: "Ghost's movement speed is faster in colder rooms during hunts", ghost: 'Hantu' },
  { id: 'poor_detection', label: "Ghost won't hear/detect you outside of 2.5 meters during hunt", ghost: 'Yokai' },
  { id: 'fast_near_electronics', label: 'Ghost moves faster near active equipment during hunt (activate flashlight near the ghost during safe loop)', ghost: 'Raiju' },
  { id: 'larger_equipment_range', label: 'Effects equipment at 15 meters instead of 10 meters during hunt', ghost: 'Raiju' },
  { id: 'silent_footsteps', label: "Cannot hear ghost's footsteps when on the same storey until within 12m range during hunts (test with flashlight standard 10m disruption)", ghost: 'Myling' },
  { id: 'alternating_speed', label: 'Hunt speed alternates between slightly slower and faster than normal on each new hunt', ghost: 'The Twins' },
  { id: 'changes_model', label: 'Ghost model changes briefly during hunt', ghost: 'Obake' },
  { id: 'slows_on_meds', label: 'Ghost hunt speed is tied to sanity (slows when taking meds mid hunt)', ghost: 'Moroi' },
  { id: 'fast_far_slow_close', label: "Ghost has fastest hunt movement speed in game when far, slowest movement speed in game when close", ghost: 'Deogen' },
  { id: 'cant_turn_lights', label: 'Ghost cannot turn on lights', ghost: 'Mare' },
  { id: 'turns_off_lights', label: "Ghost turns lights off immediately after they're turned on (when ghost is within 4 meters)", ghost: 'Mare' },
  { id: 'prefers_light_events', label: 'Prefers light bursting events and turning lights off', ghost: 'Mare' },
  { id: 'wanders_to_dark', label: "Wanders out of rooms with light into rooms without light (only lights effected by breaker count, wandering happens outside of hunting)", ghost: 'Mare' },
  { id: 'screams_parabolic', label: 'Unique scream heard on parabolic mic', ghost: 'Banshee' },
  { id: 'hunt_speed_decreases', label: "Ghost has gradually slower hunt speeds as players spend more time in the ghost's favorite room", ghost: 'Thaye' },
  { id: 'double_slam', label: 'Ghost double touches doors and slams doors', ghost: 'Yurei' },
  { id: 'interacts_main_door', label: 'Ghost interacts with the main door outside of ghost event and hunts', ghost: 'Yurei' },
  { id: 'never_changes_rooms', label: 'Ghost never changes favorite room', ghost: 'Goryo, Banshee' },
  { id: 'hunts_after_candles', label: 'Ghost hunts after every third flame extinguished (single candle, candelabra, lit igniter all = 1 flame)', ghost: 'Onryo' },
  { id: 'cant_light_fire', label: 'Ghost cannot light any fire sources (unless forced by a voodoo doll)', ghost: 'Onryo' },
  { id: 'no_hunt_in_room', label: "Ghost won't hunt while players are in it's favorite room", ghost: 'Shade' },
  { id: 'speed_with_breaker', label: "Ghost's hunt speed is fast when breaker is on and player is far away", ghost: 'Jinn' },
  { id: 'never_turns_off_breaker', label: 'Ghost never turns off breaker', ghost: 'Jinn' },
  { id: 'hunts_20s', label: 'Hunts again in 20 seconds instead of 25 (easiest to test at 0 sanity)', ghost: 'Demon' },
  { id: 'speed_when_hiding', label: "Ghost's hunt speed is extremely slow when player isn't detected, and very fast when it detects a player", ghost: 'Revenant' },
  { id: 'copies_ghost_traits', label: 'Copies other ghost\'s traits every 30s-2min', ghost: 'The Mimic' }
];

export const huntEvidenceMap = {
  'hunts_after_smudge_1': ['Demon'],
  'hunts_after_smudge_3': ['Spirit'],
  'no_salt': ['Wraith'],
  'throws_far': ['Poltergeist'],
  'throws_multiple': ['Poltergeist'],
  'disappears_photo': ['Phantom'],
  'less_visible_hunt': ['Phantom'],
  'more_visible_hunt': ['Oni'],
  'no_ghost_mist': ['Oni'],
  'breath_breaker_off': ['Hantu'],
  'never_turns_on_breaker': ['Hantu'],
  'faster_cold_rooms': ['Hantu'],
  'poor_detection': ['Yokai'],
  'fast_near_electronics': ['Raiju'],
  'larger_equipment_range': ['Raiju'],
  'silent_footsteps': ['Myling'],
  'alternating_speed': ['The Twins'],
  'changes_model': ['Obake'],
  'slows_on_meds': ['Moroi'],
  'fast_far_slow_close': ['Deogen'],
  'cant_turn_lights': ['Mare'],
  'turns_off_lights': ['Mare'],
  'prefers_light_events': ['Mare'],
  'wanders_to_dark': ['Mare'],
  'screams_parabolic': ['Banshee'],
  'hunt_speed_decreases': ['Thaye'],
  'double_slam': ['Yurei'],
  'interacts_main_door': ['Yurei'],
  'never_changes_rooms': ['Goryo', 'Banshee'],
  'hunts_after_candles': ['Onryo'],
  'cant_light_fire': ['Onryo'],
  'no_hunt_in_room': ['Shade'],
  'speed_with_breaker': ['Jinn'],
  'never_turns_off_breaker': ['Jinn'],
  'hunts_20s': ['Demon'],
  'speed_when_hiding': ['Revenant'],
  'copies_ghost_traits': ['The Mimic']
};